#Problem 1 - Array creation:

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a specific value (e.g., 7)
fill_value_array = np.full((3, 3), 7)
print("\nArray filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with the same shape and type as a given array
given_array = np.array([[5, 6], [7, 8]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array with the same shape as the given array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes Array with the same shape as the given array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("\nConverted NumPy Array from list:\n", converted_array)


Empty Array (2x2):
 [[ 4.67559708e-310  0.00000000e+000]
 [-2.92437774e-265  6.67981245e-310]]

All-Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with the same shape as the given array:
 [[0 0]
 [0 0]]

Ones Array with the same shape as the given array:
 [[1 1]
 [1 1]]

Converted NumPy Array from list:
 [1 2 3 4]


#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("\nArray with values from 10 to 49:\n", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
reshaped_matrix = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", reshaped_matrix)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array (size 30):\n", random_array)
print("Mean of the random array:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\nRandom 10x10 Matrix:\n", random_matrix)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element replaced by 1:\n", zero_array)

# 7. Reverse an array [1, 2, 0, 0, 4, 0]
array_to_reverse = np.array([1, 2, 0, 0, 4, 0])
reversed_array = array_to_reverse[::-1]
print("\nReversed Array:\n", reversed_array)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)



Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array (size 30):
 [0.55038634 0.98312284 0.02685189 0.26139349 0.69287104 0.13775259
 0.94867841 0.21403845 0.85080193 0.17362749 0.81208649 0.0457903
 0.06203666 0.3145752  0.25298487 0.49213062 0.03463285 0.4725515
 0.9721152  0.07646033 0.60758581 0.10469382 0.06939379 0.84567466
 0.15399091 0.81197831 0.69690845 0.56129125 0.5035879  0.73070877]
Mean of the random array: 0.44869007123230703

Random 10x10 Matrix:
 [[0.3781157  0.01102814 0.34383524 0.89610143 0.73789636 0.8498302
  0.81743481 0.04078509 0.10581317 0.6168281 ]
 [0.62839692 0.28331315 0.84888187 0.86625294 0.02499128 0.7272017
  0.65467018 0.23353311 0.82614055 0.26108543]
 [0.11729555 0.42315895 0.16882225 0.20140764 0.35489547 0.

#Problem - 3: Array Operations:

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add two arrays
add_result = x + y
print("\nAddition of x and y:\n", add_result)

# 2. Subtract two arrays
subtract_result = x - y
print("\nSubtraction of x and y:\n", subtract_result)

# 3. Multiply array with an integer
multiplied_array = x * 3
print("\nArray x multiplied by 3:\n", multiplied_array)

# 4. Find the square of each element
squared_array = x ** 2
print("\nSquare of each element in x:\n", squared_array)

# 5. Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot Product of v and w:", dot_vw)
print("Dot Product of x and v:\n", dot_xv)
print("Dot Product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows
concat_xy_row = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along rows:\n", concat_xy_row)

# 7. Concatenate v and w along columns
concat_vw_col = np.column_stack((v, w))
print("\nConcatenate v and w along columns:\n", concat_vw_col)

# Explanation: Concatenating x and v fails because their dimensions differ
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nConcatenating x and v results in error:", e)



Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Array x multiplied by 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot Product of v and w: 219
Dot Product of x and v:
 [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Concatenating x and v results in error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


#Problem - 4: Matrix Operations:

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
inverse_A = np.linalg.inv(A)
identity_proof = np.dot(A, inverse_A)
print("\nA * A^-1:\n", identity_proof)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)

# 3. Prove (AB)^T = B^T * A^T
transpose_AB = AB.T
transpose_BA = np.dot(B.T, A.T)
print("\n(AB)^T:\n", transpose_AB)
print("B^T * A^T:\n", transpose_BA)

# Solve the system of equations
coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])
solution = np.linalg.solve(coefficients, constants)
print("\nSolution to the system of linear equations:\n", solution)



A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]

Solution to the system of linear equations:
 [ 2.  1. -2.]


#Problem 5: Performance Comparison

In [ ]:
import time

size = 1_000_000

# Generate Python lists and NumPy arrays
list1, list2 = list(range(size)), list(range(size))
array1, array2 = np.arange(size), np.arange(size)

# 1. Element-wise addition
start = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("\nPython Lists Addition Time:", end - start)

start = time.time()
numpy_addition = array1 + array2
end = time.time()
print("NumPy Addition Time:", end - start)

# 2. Element-wise multiplication
start = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("\nPython Lists Multiplication Time:", end - start)

start = time.time()
numpy_multiplication = array1 * array2
end = time.time()
print("NumPy Multiplication Time:", end - start)

# 3. Dot product
start = time.time()
list_dot_product = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print("\nPython Lists Dot Product Time:", end - start)

start = time.time()
numpy_dot_product = np.dot(array1, array2)
end = time.time()
print("NumPy Dot Product Time:", end - start)

# 4. Matrix multiplication
matrix_size = 1000
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
numpy_matrix1 = np.array(list_matrix1)
numpy_matrix2 = np.array(list_matrix2)

start = time.time()
list_matrix_multiplication = [
    [sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)]
    for row in list_matrix1
]
end = time.time()
print("\nPython Lists Matrix Multiplication Time:", end - start)

start = time.time()
numpy_matrix_multiplication = np.dot(numpy_matrix1, numpy_matrix2)
end = time.time()
print("NumPy Matrix Multiplication Time:", end - start)



Python Lists Addition Time: 0.31280088424682617
NumPy Addition Time: 0.0062999725341796875

Python Lists Multiplication Time: 0.3392512798309326
NumPy Multiplication Time: 0.002757549285888672

Python Lists Dot Product Time: 0.33383703231811523
NumPy Dot Product Time: 0.0021314620971679688

Python Lists Matrix Multiplication Time: 182.86501145362854
NumPy Matrix Multiplication Time: 2.332002878189087
